[package]
name = "dynamics-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "dynamics"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }
collider = { workspace = true}
numpy = { workspace = true }

inertia = { path = "../crates/dynamics-inertia" }
joint = { path = "../crates/dynamics-joint" }
model = { path = "../crates/dynamics-model" }
parse = { path = "../crates/dynamics-parse" }
spatial = { path = "../crates/dynamics-spatial" }

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]
all-features = true